start_directory: ~/dev/projects/startpage
session_name: startpage
windows:
  - window_name: editor
    panes:
      - shell_command:
          - nvim
  - window_name: server
    panes:
      - shell_command:
          - five-server
